initial cleanup

diff --git a/zoneinit b/zoneinit
--- a/zoneinit
+++ b/zoneinit
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Copyright 2013, Joyent. Inc. All rights reserved.
+# Copyright 2017, Joyent. Inc.
 
 PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
 export PATH
@@ -12,7 +12,8 @@ set -o xtrace
 smf_is_globalzone && exit ${SMF_EXIT_OK}
 
 # Set basedir and default config file
-ZONEINIT_INCLUDES=@ZONEINIT_DIR@/includes
+ZONEINIT_DIR=@ZONEINIT_DIR@
+ZONEINIT_INCLUDES=$ZONEINIT_DIR/includes
 ZONECONFIG=/root/zoneconfig
 
 # This script should only continue if
@@ -25,37 +26,41 @@ ZONECONFIG=/root/zoneconfig
 
 # Pre-create /var/svc/provisioning if /root/zoneconfig exists
 # to stay backwards compatible.
-
-[ -e ${ZONECONFIG} ] && touch /var/svc/provisioning
+if [[ -e $ZONECONFIG ]]; then
+	touch /var/svc/provisioning
+fi
 
 # Do nothing if not under SMF, not provisioning, or already done.
 
-if [[ ! "${SMF_METHOD}" == "start" ]] || \
-   [[ ! -e /var/svc/provisioning ]] || \
-   [[ $(svcprop -p application/done zoneinit) =~ true ]]; then
-  exit ${SMF_EXIT_OK}
+if [[ $SMF_METHOD != 'start' || \
+   ! -e /var/svc/provisioning || \
+   "$(svcprop -p application/done zoneinit)" =~ true ]]; then
+
+	exit ${SMF_EXIT_OK}
 fi
 
 function log {
-  local WHERE=$(basename ${INC-zoneinit})
-  echo "${WHERE}: $1"
+	local WHERE=$(basename "${INC-zoneinit}")
+	echo "${WHERE}: $1"
 }
 
 function exit_handler {
-  local WHERE=$(basename ${INC-zoneinit})
-  local EXITCODE=${2:-95}
+	local WHERE=$(basename "${INC-zoneinit}")
+	local EXITCODE=${2:-95}
 
-  if [ ${EXITCODE} -gt 0 ]; then
-    echo "${WHERE}: $1 ${EXITCODE}"
+	if [ ${EXITCODE} -gt 0 ]; then
+		echo "${WHERE}: $1 ${EXITCODE}"
 
-    # Renaming 'provisioning' to 'provision_failure' tells the provisioner
-    # that we failed and the machine is no good
+		# Renaming 'provisioning' to 'provision_failure' tells the
+		# provisioner that we failed and the machine is no good
+		if [[ -e /var/svc/provisioning ]]; then
+			mv /var/svc/provision{ing,_failure}
+		fi
 
-    [ -e /var/svc/provisioning ] && mv /var/svc/provision{ing,_failure}
-
-    # Status 95 tells the SMF restarter to fail fatally (not try again)
-    exit ${SMF_EXIT_ERR_FATAL}
-  fi
+		# Status 95 tells the SMF restarter to fail fatally (not try
+		# again)
+		exit "$SMF_EXIT_ERR_FATAL"
+	fi
 }
 
 trap 'exit_handler "received exit status" $?' EXIT
@@ -64,19 +69,16 @@ START_TIME=$(date +%s)
 log "(start)"
 
 # Pull in and execute all operations from the 'includes' directory
-for INC in ${ZONEINIT_INCLUDES}/*.sh
-do
-  log "(start)"
-  source ${INC}
+for INC in "$ZONEINIT_INCLUDES"/*.sh; do
+	log "(start)"
+	source "$INC"
 done
 unset INC
 
 END_TIME=$(date +%s)
-RUN_TIME=$((END_TIME-START_TIME))
-if [ ${RUN_TIME} -gt 0 ]; then
-  log "total runtime ${RUN_TIME} seconds"
-fi
+RUN_TIME=$((END_TIME - START_TIME))
+log "total runtime $RUN_TIME seconds"
 
 # provisioner takes over
 log "(finish)"
-exit ${SMF_EXIT_OK}
+exit "$SMF_EXIT_OK"
